# Generated by Django 3.0.6 on 2020-05-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cable',
            name='conductor',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='cable',
            name='cross_section',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cable',
            name='insulation',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='cable',
            name='voltage_rating',
            field=models.CharField(max_length=20),
        ),
    ]
