# Generated by Django 3.0.6 on 2020-05-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0002_auto_20200520_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cable',
            name='cross_section',
            field=models.FloatField(),
        ),
    ]
