# Generated by Django 3.0.6 on 2020-05-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0003_auto_20200520_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='cable',
            name='impedance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cable',
            name='nom_current_rating',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cable',
            name='short_circuit_1s',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
    ]
